### ISSUE TITLE
Adding "Previous" and "Next" buttons in the "Table of contents" of "contributing.md"

### ISSUE THREAD

**Issue by PJBayani** [freeCodeCampManila/blog#6]
As I was reading thru the items in the "table of contents" of the "contributing.md" , i was constantly clicking on back to get to the previous page and then clicking on the next item. Normally, we should be able to move directly into the next entry. I don't know if adding a "previous" and "next" button is possible but it if it can be added, it will be a better user experience. Thanks

**Comment by RemLampa** [comment]
Yes, it is possible! There are stuff here that I intentionally (and unintentionally) left out for contributors to find and figure out. Lol.

Parang Easter Egg hunting, but with code.
